// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfxbVmbI4DtGqljy3FBdlAXki-t9-4tnA',
    appId: '1:262179450637:web:10b8a48989726e7f4e0a44',
    messagingSenderId: '262179450637',
    projectId: 'travel-buddy-bknd',
    authDomain: 'travel-buddy-bknd.firebaseapp.com',
    storageBucket: 'travel-buddy-bknd.appspot.com',
    measurementId: 'G-KH6H7CT3G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfdAv8q7-w0ZgUwT-0pWfbtEXvlilGreI',
    appId: '1:262179450637:android:181e08f15a51a6b24e0a44',
    messagingSenderId: '262179450637',
    projectId: 'travel-buddy-bknd',
    storageBucket: 'travel-buddy-bknd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvGbqcu7IGqXLHmrrv6f50uOcgjSSaqkg',
    appId: '1:262179450637:ios:2759a89d3f39645f4e0a44',
    messagingSenderId: '262179450637',
    projectId: 'travel-buddy-bknd',
    storageBucket: 'travel-buddy-bknd.appspot.com',
    iosBundleId: 'com.example.travelBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvGbqcu7IGqXLHmrrv6f50uOcgjSSaqkg',
    appId: '1:262179450637:ios:d095a53e0cce4a2c4e0a44',
    messagingSenderId: '262179450637',
    projectId: 'travel-buddy-bknd',
    storageBucket: 'travel-buddy-bknd.appspot.com',
    iosBundleId: 'com.example.travelBuddy.RunnerTests',
  );
}
